// <auto-generated />
namespace MyVideoTraining.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01AddMobile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01AddMobile));
        
        string IMigrationMetadata.Id
        {
            get { return "201504281041539_01 Add Mobile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
