// <auto-generated />
namespace MyVideoTraining.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PatientDemographics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PatientDemographics));
        
        string IMigrationMetadata.Id
        {
            get { return "201504301201511_Patient Demographics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
